title: BMOL Digital
description: "Brenden Moloney's Portfolio"
baseurl: "" # change if serving from a subpath (e.g., /repo-name)
url: "https://realBMOLDIGITAL.github.io" # replace USERNAME
plugins:
  - jekyll-feed

markdown: kramdown
permalink: /:title/
