title: BMOL Digital
description: "A Jekyll site for BMOL Digital"
baseurl: "" # change if serving from a subpath (e.g., /repo-name)
url: "https://USERNAME.github.io" # replace USERNAME
theme: jekyll-theme-cayman
plugins:
  - jekyll-feed

markdown: kramdown
permalink: /:title/
